# Generated by Django 2.0.4 on 2018-05-07 06:53

import blog.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='static/media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=20, validators=[blog.models.validate_tag_name]),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
