# Generated by Django 2.0.4 on 2018-05-06 12:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180505_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=20, validators=[blog.models.validate_tag_name]),
            preserve_default=False,
        ),
    ]
