# Generated by Django 2.0.4 on 2018-05-07 07:35

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180507_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='static/media', verbose_name='Image'),
        ),
    ]
